### ISSUE TITLE
README typo

### ISSUE THREAD

**Issue by NathanGavenski** [hanruihua/ir-sim#28]
Hey, great project.

Just wanted to let you know there is a small mistake on your readme.md and didn't want to open a PR for that.

```yaml
world:
  height: 10  # the height of the world
  width: 10   # the height of the world
  step_time: 0.1  # 10Hz calculate each step
  sample_time: 0.1  # 10 Hz for render and data extraction 
  offset: [0, 0] # the offset of the world on x and y 
```

Should be **width** instead of **height** on the `width` param.
