### ISSUE TITLE
obstacles

### ISSUE THREAD

**Issue by Yajoker** [hanruihua/ir-sim#60]
Hello, can dynamic obstacles be added to this simulator?

**Comment by hanruihua** [comment]
Hi,

The dynamic, static, and map obstacles can be appear together. You can simply add the different type obstacles in the yaml, e.g.: 

```
obstacle:
  - number: 10
    distribution: {name: 'manual'}
    shape:
      - {name: 'polygon', random_shape: true, center_range: [5, 10, 40, 30], avg_radius_range: [0.5, 2]}  # radius
   
  - kinematics: {name: 'omni'}
    behavior: {name: 'dash'}
    shape: {name: 'circle', radius: 1.0}  # radius
    state: [5, 5, 0]  
```

You can also refer to the grip map yaml: https://github.com/hanruihua/ir-sim/blob/main/irsim/usage/10grid_map/grid_map.yaml, which add the obstacles on the map.
