### ISSUE TITLE
Add option to have acceptable end goal errors (x,y, theta)

### ISSUE THREAD

**Issue by ljaniec** [hanruihua/ir-sim#74]
Hello,

I wanted to use the `irsim` to simulate an Ackerman car with a basic motion to the point, but the car started moving in the circles at the end:

![Image](https://github.com/user-attachments/assets/50c0b57a-b66d-42ad-a198-e9b9bf71ed29)

I think adding the option to have acceptable end goal position error would be good.

My file to test is a modification of `02robot_world`:
-   `car_world.yaml`

```yaml
world:
  height: 50 # the height of the world
  width: 50 # the width of the world
  step_time: 0.01 # 10Hz calculate each step
  sample_time: 0.1 # 10 Hz for render and data extraction
  offset: [0, 0] # the offset of the world on x and y

robot:
  - kinematics: { name: "acker" } # omni, diff, acker
    shape: { name: "rectangle", length: 4.6, width: 1.6, wheelbase: 3 }
    state:
      - [1, 1, 0, 0]
    goal:
      - [25, 25, 0]
      - [15, 25, 0]
    vel_max:
      - [4, 1]
    behavior: { name: "dash" } # move toward to the goal directly
    plot:
      show_trajectory: True
```

- `robot_world.py`

```python
import irsim

# env = irsim.make('robot_world.yaml')
# env = irsim.make("robot_omni_world.yaml")
env = irsim.make("car_world.yaml")
# env = irsim.make("robot_polygon_world.yaml")

for i in range(10000):
    env.step()
    env.render(0.01)

    if env.done():
        break

env.end()
```

Additional question - how can I implement my own kinematic controller? 

I would like to use `irsim` with a group of robots that follows the-best-they-can Bezier splines, with orders to stop/start their movement from the supervisor controller (using Multi-Agent Path Finding on free-range non-rectangular maps and deadlock-free coordination). 

Any suggestions for this would be greatly appreciated. For now I am working with SimPy to model their movement discreetly.
